#!/bin/bash

if [ "$#" -lt 2 ]
then
    echo "Usage: generate-bib-per-category <file.bib> Author [--delurl]"
    exit 1
fi

BIBFILE=$1
AUTHOR=$2
DELURL=0

shift 2

while (( "$#" ))
do
    if [[ "$1" == "--delurl" ]]
    then 
        DELURL=1
    fi
    shift
done

bib2bib -s year -s month -r -ob publications.bib -c "author : \"$AUTHOR\" or (editor : \"$AUTHOR\" and (\$type = \"PROCEEDINGS\" or \$type = \"BOOK\"))" "$BIBFILE"

if [ "$DELURL" == "1" ]
then
	cat publications.bib | sed -n '
1h
1!H
$ {
	g
	s/,\n[ ]*url[ ]*=[ ]*{[^}]*}//g
	p
}
' > _publications.bib
	mv _publications.bib publications.bib
fi

bib2bib -ob journals.bib -c "\$type = \"ARTICLE\"" publications.bib
bib2bib -ob conferences.bib -c "\$type = \"INPROCEEDINGS\"" publications.bib
bib2bib -ob unpublished.bib -c "\$type = \"UNPUBLISHED\"" publications.bib
bib2bib -ob books.bib -c "not booktitle : \"Newsletter\" and \$type = \"INCOLLECTION\"" publications.bib
bib2bib -ob edited.bib -c "editor : \"$AUTHOR\" and (\$type = \"PROCEEDINGS\" or \$type = \"BOOK\")" publications.bib
bib2bib -ob other.bib -c  "author : \"$AUTHOR\" and not \$type = \"ARTICLE\" and (not \$type = \"INCOLLECTION\" or booktitle : \"Newsletter\") and not \$type = \"INPROCEEDINGS\" and not \$type = \"UNPUBLISHED\"" publications.bib
